# PostgreSQL. Versions 8.2 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

test:
  <<: *default
  database: auctionsite_test

development:
  <<: *default
  database: auctionsite_dev

production:
  <<: *default
  database: auctionsite_production
  username: auctionsite
  password: <%= ENV['auctionsite_DATABASE_PASSWORD'] %>
